### ISSUE TITLE
Problem with rendering formula forming `y = sin(ax) / b`

### ISSUE THREAD

**Issue by hezicyan** [nocpiun/calcium#1]
## Description

Some points on the curve will suddenly jump to zero.

## Reproduction

Input as described.

## Screenshot

![y=sin(x)/1](https://github.com/nocpiun/calcium/assets/52601326/c505510e-9c56-48f3-982b-ae55ec69d1b0)

![y=sin(2x)/3](https://github.com/nocpiun/calcium/assets/52601326/84d75bed-4306-4c58-a007-23c020dcb21b)

**Comment by NriotHrreion** [comment]
This has something to do with the v8 engine....
![image](https://github.com/nocpiun/calcium/assets/50199130/9cfaf2f0-6032-47ff-90a0-b188d4b942eb)
