### ISSUE TITLE
Advice on making a distinction between positive infinity and negative infinity in the general function

### ISSUE THREAD

**Issue by ChangZing** [nocpiun/calcium#10]
### Description
In the general functions, the result of dividing a negative number by zero suggests going from positive infinity to negative infinity.
![image](https://github.com/nocpiun/calcium/assets/90511645/d9df03eb-9655-42d6-a93e-749633d74c51)

**Comment by NriotHrreion** [comment]
https://github.com/nocpiun/calcium/commit/684721e3dbfa4ba5b394b39175ed391b7cf09ff5
