### ISSUE TITLE
The calculation result of the factorial of a number less than one is incorrect

### ISSUE THREAD

**Issue by ChangZing** [nocpiun/calcium#12]
### Description
The calculation result of the factorial of a number less than one (except 0) is incorrect.

### Reproduction
Input a factorial function involving numbers less than one (except 0).

### Expected behavior
It is expected that the calculation result of the factorial of a number less than one is correct.

### Screenshots
![image](https://github.com/nocpiun/calcium/assets/90511645/1ea7761e-1d85-451a-97e4-5da222ced5e2)

**Comment by NriotHrreion** [comment]
I don't know how to calculate the nonintegral factorial number...
