### ISSUE TITLE
显示的数值

### ISSUE THREAD

**Issue by maxin007** [nocpiun/calcium#14]
### Description很好的一个计算器。太棒了。能够多行显示数值 不然输入的多了就挡住了之前的数值
![IMG_3373](https://github.com/nocpiun/calcium/assets/22965672/055995ab-a582-4984-9357-fb80721a46e9)

**Comment by maxin007** [comment]
是的。我用手机iPhone11的浏览器。我将它发送到了屏幕上发自我的 iPhone在 2023年12月2日，23:22，NoahHrreion ***@***.***> 写道：﻿
请问你是用浏览器打开的吗？我这里没办法复现你的问题，照说下面应该会有滚动条可以拖动的。
3b3604a85b1c9791fb2139995a80731.jpg (view on web)

**Comment by NriotHrreion** [comment]
> 是的。我用手机iPhone11的浏览器。我将它发送到了屏幕上发自我的 iPhone在 2023年12月2日，23:22，NoahHrreion ***@***.***> 写道：﻿ 请问你是用浏览器打开的吗？我这里没办法复现你的问题，照说下面应该会有滚动条可以拖动的。 3b3604a85b1c9791fb2139995a80731.jpg (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

你可以尝试直接拖拽那些数字，浏览器会有自带的滚动条给你拖拽
