### ISSUE TITLE
`2sin(x)cos(x)` being equal to `sin(x)`

### ISSUE THREAD

**Issue by hezicyan** [nocpiun/calcium#2]
## Description

`2sin(x)cos(x)` equals `sin(x)`, which is expected to be equal to `sin(2x)`.

## Reprocution

Input `2sin(x)cos(x)` compared with `sin(x)`.

### `2sin(x)cos(x)`, which is the formula inputted
![Snipaste_2023-08-09_15-58-24](https://github.com/nocpiun/calcium/assets/52601326/cb6b7716-084f-4d36-a582-eefb8a9ffa4a)

### `sin(x)`, which is the result formed to
![Snipaste_2023-08-09_15-59-04](https://github.com/nocpiun/calcium/assets/52601326/9870ef61-09aa-460e-9ad6-9a337b0af8c8)

### `sin(2x)`, which is expected
![Snipaste_2023-08-09_15-58-48](https://github.com/nocpiun/calcium/assets/52601326/3659a623-8f46-4584-ae72-58f4beb3663b)

**Comment by NriotHrreion** [comment]
This has something to do with the following:
![image](https://github.com/nocpiun/calcium/assets/50199130/b60e6a13-0ff0-4034-a0ca-4072d3b8a823)
