### ISSUE TITLE
Problem with the function image when the trigonometric functions are accompanied by a coefficient or are operated

### ISSUE THREAD

**Issue by ChangZing** [nocpiun/calcium#4]
### Description
There are some problems with the function image when the trigonometric function is accompanied by a coefficient or the trigonometric function is operated
### Reproduction
Input as described.
### Screenshot
![image](https://github.com/nocpiun/calcium/assets/90511645/3853eecc-3d9f-4ad2-9b15-c36577ff64bb)
![image](https://github.com/nocpiun/calcium/assets/90511645/8acda740-271a-4b2f-8283-98c50f630f93)

**Comment by Hallon233** [comment]
@ChangZing you are not attempting your math homework, are you?
