### ISSUE TITLE
Problem with the function image about the interruptive and asymmetrical rendering of logarithmic functions

### ISSUE THREAD

**Issue by ChangSakura** [nocpiun/calcium#6]
### Description
In the function image function, the rendering of logarithmic functions will have interruption and asymmetry problems.
### Reproduction
Input logarithmic functions including trigonometric functions.
### Screenshot
![image](https://github.com/nocpiun/calcium/assets/90511645/b0ad4901-032f-4a2b-813b-aebe4e1d0b10)

**Comment by NriotHrreion** [comment]
In desmos, it performs similarly
![image](https://github.com/nocpiun/calcium/assets/50199130/1ee05e49-82b8-4e9b-af33-1fa925d6c79b)
So I can only decrease the delta x while drawing the function, and can't fix it completely.
