### ISSUE TITLE
Problem with the function image about coefficients

### ISSUE THREAD

**Issue by ChangZing** [nocpiun/calcium#7]
### Description
In the function image, the rendering functions with coefficients has problems.

### Reproduction
Input functions with some coefficients.

### Expected behavior
It is expected that in the function image, the rendering of functions with coefficients is correct.

#### [Example 1]
![image](https://github.com/nocpiun/calcium/assets/90511645/9d50807d-e7a8-48bb-99b8-15c44b7a3cac)
After enclosing the coefficients in parentheses, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/8148a428-24ba-4507-bbe5-48054bd773eb)
#### [Example 2]
![image](https://github.com/nocpiun/calcium/assets/90511645/c9ab3345-8123-477f-b575-63aa9b07d345)
After enclosing the coefficients in parentheses, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/ff57982d-200c-4c0d-8f4e-cae9b4a05d7c)
#### [Example 3]
![image](https://github.com/nocpiun/calcium/assets/90511645/c198b9fa-da14-4313-80f0-a77e0ea66815)
After enclosing the coefficients in parentheses, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/d030fceb-9bef-4ffa-b213-0e33667fc16c)
#### [Example 4]
![image](https://github.com/nocpiun/calcium/assets/90511645/c02ebce7-3464-4a8c-a69d-58f5d0937ff3)
After removing the brackets where the coefficients are, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/4361c748-c41c-4002-b375-618f9ccf355f)
#### [Example 5]
![image](https://github.com/nocpiun/calcium/assets/90511645/19c2f57e-4064-4fac-b11d-e3cd06363cf2)
After removing the brackets where the coefficients are, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/e7781210-9b07-42b2-890a-bbac38136d99)

**Comment by GregTaoo** [comment]
This problem may be caused by `π`. 
Can also try `y=sin(π)`

**Comment by GregTaoo** [comment]
try `y=sin(eπx)` and `y=sin(xeπ)`
 `y=sin(eπx)` wouldn't be displayed

**Comment by GregTaoo** [comment]
Also try `y=eπx` and `y=x(eπ)`

**Comment by NriotHrreion** [comment]
![image](https://github.com/nocpiun/calcium/assets/50199130/b8148cc8-b000-4ba4-8029-7d394ecba828)
