### ISSUE TITLE
In the general function, the calculation result of the trigonometric function with a coefficient before shows a precision error

### ISSUE THREAD

**Issue by ChangZing** [nocpiun/calcium#8]
### Description
In the general function, the calculation result of the trigonometric function with a coefficient before shows a precision error.

### Reproduction
Input the trigonometric function with a coefficient before.

### Expected behavior
It is expected that in the general function, the calculation result of the trigonometric function with a coefficient before is correct.

#### [Example 1]
![image](https://github.com/nocpiun/calcium/assets/90511645/46f504c7-ad63-4cd3-8c30-e9e75d0976b9)
After enclosing the trigonometric functions in parentheses, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/96943ca6-67ef-42b2-9a29-e2ae0edae2a1)

#### [Example 2]
![image](https://github.com/nocpiun/calcium/assets/90511645/140cdeea-26e0-4f43-8ab0-7b1df2baba02)
After enclosing the trigonometric functions in parentheses, the image renders fine:
![image](https://github.com/nocpiun/calcium/assets/90511645/a009b02f-440c-428e-b706-9314cb9351d3)

**Comment by NriotHrreion** [comment]
This has something to do with the v8 engine
![image](https://github.com/nocpiun/calcium/assets/50199130/82ca733f-1225-4cc5-ab52-7aadfce847d1)
